[custom]
;WENJUN规则，不要随意改关键字，除非清楚自己真实需求，引用mihomo规则集

;去广告：支持
;自动测速：不支持
;常用软件分流：支持
;增强中国ip段：支持
;增强GFW：支持

;设置规则标志位
ruleset=🌏 我的直连,https://raw.githubusercontent.com/w53227871-max/openclash-rules/refs/heads/main/rules/Chinadirect.list
ruleset=🌏 宽带直连,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/classical/private.list
ruleset=🌏 宽带直连,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/classical/steam@cn.list
ruleset=🌏 宽带直连,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/classical/cn.list
ruleset=Ⓜ️ 微软服务,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/classical/microsoft.list
ruleset=Ⓜ️ ONEDRIVE,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/classical/onedrive.list
ruleset=🍎 apple,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/classical/apple.list
ruleset=🍎 apple,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geoip/classical/apple.list
ruleset=🎪 telegram,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/classical/telegram.list
ruleset=🎪 telegram,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geoip/classical/telegram.list
ruleset=🚢 ai,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/classical/openai.list
ruleset=🏛️ spotify,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/classical/spotify.list
ruleset=🎡 steam,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/classical/steam.list
ruleset=🚀 Youtube,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/classical/youtube.list
ruleset=🛰️ Netflix,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/classical/netflix.list
ruleset=🛰️ Netflix,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geoip/classical/netflix.list
ruleset=🏚️ bilibili,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/classical/bilibili.list
ruleset=🏚️ bilibili,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geoip/classical/bilibili.list
ruleset=🚀 节点选择,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/classical/proxy.list
ruleset=🌏 宽带直连,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geoip/classical/private.list
ruleset=🌏 宽带直连,[]GEOIP,CN
ruleset=☄️ 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=Ⓜ️ 微软服务`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=Ⓜ️ ONEDRIVE`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=🍎 apple`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=🎪 telegram`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=🚢 ai`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=🏛️ spotify`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=🎡 steam`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=🚀 Youtube`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=🛰️ Netflix`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=🏚️ bilibili`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=🌏 我的直连`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=🌏 宽带直连`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=☄️ 漏网之鱼`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=🇭🇰 香港节点`select`(港|HK|hk|Hong Kong|HongKong|hong kong)
custom_proxy_group=🇺🇸 美国节点`select`(美|US|United States|Oregon|Los Angeles)
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;luck
