[custom]
;WENJUN规则，不要随意改关键字，除非清楚自己真实需求，引用mihomo规则集
;ACL4SSR规则

;去广告：支持
;自动测速：不支持
;常用软件分流：支持
;增强中国ip段：支持
;增强GFW：支持

;设置规则标志位
ruleset=🌏 我的直连,https://raw.githubusercontent.com/w53227871-max/openclash-rules/refs/heads/main/rules/Chinadirect.list
ruleset=🌏 宽带直连,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/classical/nvidia.list
ruleset=🌏 宽带直连,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/classical/amd.list
ruleset=🌏 宽带直连,https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/classical/asus.list
ruleset=🌏 宽带直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🌏 宽带直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=Ⓜ️ ONEDRIVE,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📱 telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=✉️ ai,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=✉️ ai,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=🎼 spotify,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Spotify.list
ruleset=🎮 steam,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=📽️ Youtube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🎞️ bilibili,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=🎞️ bilibili,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ProxyLite.list
ruleset=🌏 宽带直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🌏 宽带直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🌏 宽带直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🌏 宽带直连,[]GEOIP,CN
ruleset=☄️ 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT
custom_proxy_group=Ⓜ️ ONEDRIVE`select`[]DIRECT
custom_proxy_group=🍎 apple`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点
custom_proxy_group=📱 telegram`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=✉️ ai`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=🎼 spotify`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=🎮 steam`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=📽️ Youtube`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=🎥 Netflix`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=🎞️ bilibili`select`[]DIRECT
custom_proxy_group=🌏 我的直连`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点
custom_proxy_group=🌏 宽带直连`select`[]DIRECT`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点
custom_proxy_group=☄️ 漏网之鱼`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]DIRECT
custom_proxy_group=🇭🇰 香港节点`select`(港|HK|hk|Hong Kong|HongKong|hong kong)
custom_proxy_group=🇺🇸 美国节点`select`(美|US|United States|Oregon|Los Angeles)
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;luck
